nut-driver-enumerator.sh.in : support massive processing of all device sections checksums faster than one by one

diff --git a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
--- a/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
+++ b/scripts/upsdrvsvcctl/nut-driver-enumerator.sh.in
@@ -327,8 +327,21 @@ upssvcconf_checksum_unchanged() {
 upslist_checksums_file() {
     # List a table of DEVNAME<TAB>CHECKSUM for devices listed in $*
     # using data from NUT configuration
+    upsconf_getAllSections_MD5_once # => UPSCONF_HASH_MD5
     for _DEV in $1 ; do
         printf '%s\t%s\n' "${_DEV}" "`upsconf_getSection_MD5 "${_DEV}"`"
+    done
+}
+
+upslist_checksums_file_once() {
+    # List a table of DEVNAME<TAB>CHECKSUM for devices listed in $*
+    # using data from NUT configuration
+    # PERF : Separate a use-case for known full list to return it ASAP?
+    upsconf_getAllSections_MD5_once # => UPSCONF_HASH_MD5
+    for _DEV in $1 ; do
+        egrep "^${_DEV}${TABCHAR}" << EOF
+${UPSCONF_HASH_MD5}
+EOF
     done
 }
 
@@ -347,7 +360,10 @@ upslist_checksums_unchanged() {
     # should get reconfigured.
     [ "${#1}" = 0 -o "${#2}" = 0 ] && return 1
 
-    CFGSUMS_FILE="`upslist_checksums_file "$1"`"
+    # Better have them all than pick bits, in this routine
+#    CFGSUMS_FILE="`upslist_checksums_file "$1"`"
+    upsconf_getAllSections_MD5_once
+    CFGSUMS_FILE="${UPSCONF_HASH_MD5}"
     CFGSUMS_SAVE="`upslist_checksums_saved "$2"`"
 
     _RES=0
@@ -539,6 +555,96 @@ upsconf_getSection_MD5() {
     calc_md5 "`upsconf_getSection "$@"`"
 }
 
+upsconf_getAllSections_MD5() {
+    # Parse the whole config in one take, producing a list
+    # of all DEVICE<TAB>CHECKSUM lines
+    upsconf_getAllSections_Hash calc_md5_stdin
+}
+
+UPSCONF_HASH_MD5=""
+upsconf_getAllSections_MD5_once() {
+    # Needed output is in UPSCONF_HASH_MD5
+    UPSCONF_HASH_RES=0
+    [ "${#UPSCONF_HASH_MD5}" = 0 ] || { return 0 ; }
+    upslist_normalizeFile_once || return    # Propagate errors upwards
+    UPSCONF_HASH_MD5="`upsconf_getAllSections_MD5`" || { UPSCONF_HASH_RES=$? ; UPSCONF_HASH_MD5="" ; }
+    return $UPSCONF_HASH_RES
+}
+
+upsconf_getSection_MD5_once() {
+    # Return checksum for device section "$1"
+    # WARNING: This is intended for mass-usage scenario, so it pre-reads
+    # and pre-calculates the whole config file's worth of section checksums
+    upsconf_getAllSections_MD5_once || return # => UPSCONF_HASH_MD5
+    egrep "^${1}${TABCHAR}" << EOF
+${UPSCONF_HASH_MD5}
+EOF
+}
+
+upsconf_getAllSections_BASE64() {
+    # Parse the whole config in one take, producing a list
+    # of all DEVICE<TAB>BASE64 lines
+    upsconf_getAllSections_Hash calc_base64_stdin
+}
+
+UPSCONF_HASH_BASE64=""
+upsconf_getAllSections_BASE64_once() {
+    # Needed output is in UPSCONF_HASH_BASE64
+    UPSCONF_HASH_RES=0
+    [ "${#UPSCONF_HASH_BASE64}" = 0 ] || { return 0 ; }
+    upslist_normalizeFile_once || return    # Propagate errors upwards
+    UPSCONF_HASH_BASE64="`upsconf_getAllSections_BASE64`" || { UPSCONF_HASH_RES=$? ; UPSCONF_HASH_BASE64="" ; }
+    return $UPSCONF_HASH_RES
+}
+
+upsconf_getAllSections_Hash() {
+    # Parse the normalized config once, producing a list of all
+    # DEVICE<TAB>SOME_HASH lines, with the hash function defined
+    # by "$@" arguments, taking on stdin the contents of a section
+    # (including its [devicename] as a start - for non-globals)
+    [ "$#" != 0 ] || return
+    upslist_normalizeFile_once || return    # Propagate errors upwards
+
+    CURR_SECTION=""
+    SECTION_CONTENT=""
+    while read LINE ; do
+        case "$LINE" in
+            \[*\ *\]|\[*"$TABCHAR"*\])
+                # Note that section-name brackets should contain a single token
+                # Fall through to add the line to contents of existing section
+                ;;
+            \[*\])
+                if [ "${#SECTION_CONTENT}" != 0 ]; then
+                    # We have some content, report it
+                    printf '%s\t%s\n' "$CURR_SECTION" "`"$@" << EOF
+$SECTION_CONTENT
+EOF`"
+                fi
+                SECTION_CONTENT="$LINE"
+                CURR_SECTION="`echo "$LINE" | sed 's,^.*\[\(\^]\)\].*,\1,'`"
+                continue
+                ;;
+            "") continue ;;
+            *)  ;; # Fall through to add the line to contents of existing section
+        esac
+        if [ -n "$SECTION_CONTENT" ]; then
+            SECTION_CONTENT="$SECTION_CONTENT
+$LINE"
+        else
+            SECTION_CONTENT="$LINE"
+        fi
+    done << EOF
+${UPSCONF_DATA}
+EOF
+
+    if [ -n "$SECTION_CONTENT" ]; then
+        echo "$SECTION_CONTENT"
+    fi
+
+    [ "$RES" = 0 ] || echo "ERROR: Section [$1] was not found in the '$UPSCONF' file" >&2
+    return $RES
+}
+
 upsconf_getSection_SDP() {
     # Use the section-driver-port subset
     upslist_normalizeFile_once || return    # Propagate errors upwards
@@ -659,11 +765,20 @@ upsconf_debug() {
 # *_stdin() routines below
 calc_md5() {
     # Tries several ways to produce an MD5 of the "$1" argument
-    _MD5="`echo "$1" | md5sum 2>/dev/null | awk '{print $1}'`" && [ -n "${_MD5}" ] || \
-    { _MD5="`echo "$1" | openssl dgst -md5 2>/dev/null | awk '{print $NF}'`" && [ -n "${_MD5}" ]; } || \
+    _MD5="`md5sum 2>/dev/null << EOF | awk '{print $1}'
+$1
+EOF`" && [ -n "${_MD5}" ] || \
+    { _MD5="`openssl dgst -md5 2>/dev/null << EOF | awk '{print $NF}'
+$1
+EOF`" && [ -n "${_MD5}" ]; } || \
     return 1
 
     echo "${_MD5}"
+}
+
+calc_md5_stdin() {
+    # Tries several ways to produce an MD5 of the stdin input
+    calc_md5 "`cat`"
 }
 
 calc_md5_file() {
@@ -675,6 +790,37 @@ calc_md5_file() {
     return 1
 
     echo "${_MD5}"
+}
+
+calc_base64() {
+    _B64="`base64 2>/dev/null << EOF
+$1
+EOF`" && [ -n "${_B64}" ] || \
+    { _B64="`openssl enc -base64 -e 2>/dev/null << EOF
+$1
+EOF`" && [ -n "${_B64}" ]; } || \
+    return 1
+
+    echo "${_B64}"
+}
+
+calc_base64_stdin() {
+    # Tries several ways to produce an MD5 of the stdin input
+    calc_base64 "`cat`"
+}
+
+calc_debase64() {
+    [ "${#1}" = 0 ] && return 0
+
+    _OUT="`base64 -d 2>/dev/null << EOF
+$1
+EOF`" && [ -n "${_OUT}" ] || \
+    { _OUT="`openssl enc -base64 -d 2>/dev/null << EOF
+$1
+EOF`" && [ -n "${_OUT}" ]; } || \
+    return 1
+
+    echo "${_OUT}"
 }
 
 smf_validFullUnitName() {
